#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
    
	char word[300];
	char name[200];
	char place[100], typeName[100];	
	char cmonth[5];   
	char ctype[5];
	char cday[5];     // 문자로 입력받을 정수들 위해 우선 배열선언 
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	//fill code here ----
	fp = fopen("schedule.dat","r");
	if(fp==NULL){
		return -1;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	while ( /* fill code here -- read from the file*/fgets(word,60,fp)!=NULL) //페이지 끝날 때 까지 한줄씩 입력 반복  
	{   
	    int i=0;
	    int j=0;
	    
	    while(word[i]!=' ')
        {
       	    name[j]=word[i];
	        i++;
	        j++;
        }
        name[j]='\0';     //이번 턴에 입력된 문자만 인식되게  
	    i++;
	    j=0;
	
  	    while(word[i]!=' ')
  	    {
  	        place[j]=word[i];
	        i++;
	        j++;
	   	}
	   	place[j]='\0';   //이번 턴에 입력된 문자만 인식되게
        i++;
	    j=0;

        while(word[i]!=' ')
	    {
            ctype[j]=word[i];
	        i++;
	        j++;

	    }
	    type= atoi(ctype);    //배열로 입력받은 수 atoi함수로 정수로 변환  
	
	    i++;
	    j=0;
	
    	while(word[i]!=' ')
    	{
            cmonth[j]=word[i];
	        i++;
	        j++;
	    }
	    month= atoi(cmonth);
	
	    i++;
	    j=0;
	
    	while(word[i]!=' ')
    	{
            cday[j]=word[i];
	        i++;
	        j++;
	    }
	    day= atoi(cday);

        printf("%s %s %i %i %i ", name, place, type, month, day);

		//fill code here -- generate genSchedInfo structure by genSchedInfo function
    	schedInfo = sched_genSchedInfo(name, place, type, month, day);    // list_addTail의 object포인터인 schedInfo에 구조체 포인터 넘겨줌  

		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);  
	}
	
	
	//fill code here ---- close the file pointer
	fclose(fp);
	
	printf("Read done! %i schedules are read\n", list_len(list));
	
/*
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//fill code here ---- 
		printf("1.print all the schedules\n");
		printf("2.search for schedules in the month\n");
		printf("3.search for schedules in the place\n");
		printf("4.search for specific type schedule\n");
		printf("5.exit");
		
		//4. get option from keyboard
		//fill code here ----
		printf("select an option :");
		scanf("%i",option);
		
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					int i=1;
					printf("________________________________________\n\n");
					printf("%i : Schedule name : %s (%s)\n");
					printf("When : %s. %i\n");
					printf("where : %s");
					printf("________________________________________\n");
				
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (/* fill code here -- convert the type and check if the type is valid )
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
  */
	return 0;
}
